version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - student_loan_project

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - student_loan_project

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka:9092'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8081'
      SCHEMA_REGISTRY_HOST_NAME: 'schema-registry'
    networks:
      - student_loan_project

  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "8082:8080"
    volumes:
      - spark-data:/data
      - ./app:/app
      - ./jars:/opt/spark/jars
    command: >
      bash -c "spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0
      --jars /opt/spark/jars/sqlite-jdbc-3.46.1.2.jar /app/spark_streaming_app.py"
    depends_on:
      - kafka
    networks:
      - student_loan_project

  kafka-producer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - student_loan_project
    volumes:
      - ./datas:/datas  # Monte le dossier local dans le conteneur Kafka Producer

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.5.0
    depends_on:
      - kafka
      - zookeeper
      - schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 1
      PORT: 9021
    networks:
      - student_loan_project

volumes:
  spark-data:  # Volume Docker pour persister les données SQLite
    driver: local

networks:
  student_loan_project:
    driver: bridge
